services:
  ht-mysql:
    image: mysql:latest
    container_name: ht-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - ht_network

  ht-tomcat:
    container_name: ht-tomcat
    build:
      context: ./tomcat
    ports:
      - "8085:8080"
      - "9010:9010"
      - "1099:1099"
    environment:
      - JAVA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=1099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost
    depends_on:
      - ht-mysql
      - ht-python-service
    networks:
      - ht_network

  ht-python-service:
    container_name: ht-python-service
    build:
      context: ./python-service
    ports:
      - "5000:5000"
    networks:
      - ht_network

  ht-otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: ht-otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    networks:
      - ht_network

  ht-jaeger:
    container_name: ht-jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    networks:
      - ht_network

volumes:
  mysql_data:


networks:
  ht_network:
